### PR TITLE
Update version requirement for laminas/laminas-code

### LINKED ISSUE #6: Change version requirement for laminas/laminas-code
Right now the composer.json has the following requirement:

```
"laminas/laminas-code": "~3.4.1|^4.0"
```

This constraint won't allow version `3.5.x`. This has the downside that it is not possible to support 7.3, 7.4. and 8.0 at once. For reference:

| laminas-code | require |
| --- | --- |
| `3.4.*` | `php: ^7.1` |
| `3.5.*` | `php: ^7.3 \|\| ~8.0.0` |
| `4.0.*` | `php: ^7.4 \|\| ~8.0.0` |

As far as I can tell, it doesn't make sense to take this upstream as the version support is explicitly why this package exists. Would it make sense to change the requirement in the composer.json to support 3.5 as well?

### PR DESCRIPTION
**Pull request by dbrumann**
Fixes #6

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
I remember why I did this :)
See failures...

**Comment by dbrumann** [comment]
Thanks. In that case I will work around this issue.

**Comment by nicolas-grekas** [comment]
I'm sure it's possible to work around the issue here also, by patching the CI script to bump the mini dep of laminas on php8, if you're up to.

**Comment by mateusz-kolecki** [comment]
Hi, this issue is also affecting me. Unfortunately, logs from the pipeline are not available. Can you tell what was wrong with `laminas/laminas-code:^3.5`?

**Comment by dbrumann** [comment]
@mateusz-kolecki I don't remember what it was specifically, but there was an inconsistency that broke the test suite with 3.5.

**Pull request closed without merging**
